# This is a convenient base image that has Node installed
FROM gatoatigrado/carrotjuice-test-base:v0.1

# Install latest deps. The base image already has a few installed
COPY ./package.json /code/package.json
RUN npm install

COPY . /code
RUN cp ./config-example.js ./config.js && make build-opt
CMD /bin/bash ./scripts/phantomjs-entrypoint.sh
